### ISSUE TITLE
Как запустить SportOrg из python

### ISSUE THREAD

**Issue by mforis** [sportorg/pysport#213]
Объясните пожалуйста, как запустить программу из python, просто необходимо использовать её с системой электронной отметки Sportiduino, но в релизе поддержка пока не добавлена. Спасибо

**Comment by daxrt** [comment]
Установите python 3.6 x32
```
git clone https://github.com/sportorg/pysport.git

cd pysport

pip install -r requirements.txt

python SportOrg.pyw
```

**Comment by mforis** [comment]
Спасибо, приеду попробую, а вообще когда релиз?

**Comment by daxrt** [comment]
Мы хотим протестировать функционал, на днях может выпустим release candidate для открытого тестирования

**Comment by daxrt** [comment]
Понятно. Думал вы знаете как использовать git

**Comment by daxrt** [comment]
Тогда нажмите кнопку download и распакуйте архив. И выполните внутри папки команду pip install -r requirements.txt

**Comment by daxrt** [comment]
Команду pip install ... надо выполнять в cmd, а не в питоне, как на скриншоте

**Comment by mforis** [comment]
Понял, пробую

**Comment by mforis** [comment]
Вы меня извините, я в этом совершенно ни чего не понимаю и пока ничего не получается...

**Comment by daxrt** [comment]
Давайте по порядку. Какие у вас проблемы?

**Comment by mforis** [comment]
Так я скачал и установил питон, скачал и распаковал архив на рабочий стол,  что делать дальше?
![image](https://user-images.githubusercontent.com/32615135/38505020-e251b234-3c1e-11e8-9d30-bb351f3fd119.png)

**Comment by daxrt** [comment]
Вот ссылка чтобы скачать архив
https://github.com/sportorg/pysport/archive/dev.zip
Дальше разархивируете например в папку 
C:\SportOrg

Затем нажимаете win + R
Пишите `cmd`
Потом пишите `cd C:\Sportorg`

**Comment by daxrt** [comment]
Скопируйте путь 
И напишите в консоли `cd путь`
Потом pip install ... 
И запускаете программу

**Comment by mforis** [comment]
C:\SportOrg>pip install -r requirements.txt
"pip" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

**Comment by daxrt** [comment]
Надо добавить в переменную среды путь до установленных программ питона

**Comment by daxrt** [comment]
Давайте продолжим по Скайпу я вам все объясню

**Comment by mforis** [comment]
К сожалению нет микрофона, давайте через TeamViewer

**Comment by daxrt** [comment]
Тогда с вас доступ

**Comment by mforis** [comment]
Да, пять секунд

**Comment by mforis** [comment]
ID:846030690 Пароль:3997

**Comment by mforis** [comment]
Извините опечатка: ID:846030696

**Comment by mforis** [comment]
![image](https://user-images.githubusercontent.com/32615135/38551009-bb278ccc-3cc0-11e8-8a0b-19e80bc31ecb.png)
Добрый день! Сегодня решил потренироваться со SportOgr, но после сохранения программа не захотела открывать файл. В чем может быть проблема?

**Comment by daxrt** [comment]
Скиньте файл

**Comment by mforis** [comment]
[Итоговое 2018.zip](https://github.com/sportorg/pysport/files/1894138/2018.zip)

**Comment by daxrt** [comment]
Вы используете версию для разработчиков, так что извиняйте.
Замените файл `memory.py` в папке `C:\SportOrg\sportorg\models\`
Расширение .txt переименуйте в .py

[memory.txt](https://github.com/sportorg/pysport/files/1894192/memory.txt)

**Comment by mforis** [comment]
К вам я вообще никаких претензий не имею, а наоборот очень благодарен вам! Да и таким образом помогаю выявлять ошибки)))

**Comment by mforis** [comment]
Спасибо, всё работает))

**Comment by daxrt** [comment]
Можете загрузить новую версию
https://github.com/sportorg/pysport/archive/dev.zip
Появились звуковые уведомления при считке. Нужно только разархивировать и запустить

**Comment by mforis** [comment]
Хорошо, спасибо!

**Comment by mforis** [comment]
![image](https://user-images.githubusercontent.com/32615135/38552666-87f62192-3cc5-11e8-8966-7d1116e2c35b.png)

**Comment by daxrt** [comment]
все таки надо сделать
`pip install -r requirements.txt`

**Comment by mforis** [comment]
Запустил, а еще такой вопрос возможна ли автоматическая печать сплита после считывания чипа? Или только вручную?

**Comment by daxrt** [comment]
Вроде и так автоматически. Вы просто поставьте галочку в меню -> Опции -> Настройка печати -> Печать сплитов. Почитайте нашу доку sportorg.o-ural.ru
