### ISSUE TITLE
В протоколе суммы времени не правильно определяются места 

### ISSUE THREAD

**Issue by kbats183** [sportorg/pysport#280]
Если в протоколе два 6-х места, то 7-ого быть не должно
![default](https://user-images.githubusercontent.com/37730459/44386831-1e048180-a53d-11e8-9d6d-4939f0ea8262.PNG)

https://github.com/sportorg/pysport/blob/f61c936ead940251a0ef2c518a12676a6159cffd/templates/result/4_sum_times.html#L119-L131

**Comment by daxrt** [comment]
Да, согласен. Я этот момент забыл рассмотреть.

**Comment by daxrt** [comment]
@kbats183 мне как то лень этим шаблоном заниматься, можешь поправить данную ошибку и создать pull request?

**Comment by kbats183** [comment]
@daxrt попробую поправить
