### ISSUE TITLE
Export in winorient

### ISSUE THREAD

**Issue by halny123** [sportorg/pysport#305]
Добрый день !
После экспорта данных в формате winorient потом невозможно открыть экспортированный файл.
Может версия программы winorienta не та ?
Какую версию нужно использовать ?

**Comment by sergeikobelev** [comment]
Добрый день. У winorient были всего 2 версии формата файла, насколько нам известно. В 2010г. произошло это изменение, у Вас должен быть Winorient старше 2010г. Присылайте Ваши файлы, разберемся!
