### ISSUE TITLE
Ошибки

### ISSUE THREAD

**Issue by rg-lab** [sportorg/pysport#312]
1. Когда дистанций ещё нет, при создании группы появляется ошибка: ERROR 'NoneType' object has no attribute 'controls'
https://github.com/sportorg/pysport/blob/35ea78a983468062a903df03032ff1b8eeaec057/sportorg/gui/tabs/memory_model.py#L372
Можно исправить так:
`control_count = len(course.controls) if course else 0`

2. При попытке изменить свойства соревнований появляется ошибка: ERROR 'PySide2.QtCore.QDateTime' object has no attribute 'toPyDateTime'
https://github.com/sportorg/pysport/blob/35ea78a983468062a903df03032ff1b8eeaec057/sportorg/gui/dialogs/event_properties.py#L127-L128
Можно исправить так:
`start_date = self.item_start_date.dateTime().toPython()`
`end_date = self.item_end_date.dateTime().toPython()`

**Comment by daxartio** [comment]
Спасибо за замечания. Не стесняйтесь делать PR в dev ветку. Вторая проблема из-за нашего перехода с PyQt на PySide2. Потихоньку всё исправляем.

**Comment by sergeikobelev** [comment]
Fixed. Исправлено. pr: https://github.com/sportorg/pysport/pull/313
