### ISSUE TITLE
Шаблон стартового протокола

### ISSUE THREAD

**Issue by halny123** [sportorg/pysport#316]
Ребята подскажите пожалуйста, как можно создать стартовый протокол такого вида.

№п.п.+mp3 ; стартовое время; "ФИО стартующих на данной минуте"
с включением минут на которых никто не стартует.

Например:

1.mp3; 0:01:00; "Иванов Иван, Петров Петр"
2.mp3; 0:02:00; ""
3.mp3; 0:03:00; "Марья Кудесница"
......
61.mp3; 1:01:00; "Муромец Илья, Горыныч Змей"

Сделал часы которые озвучивают ФИО участников на старте, а для конвертации ФИО в mp3 нужен такой формат.

**Comment by daxartio** [comment]
Тебе надо выгрузить стартовый протокол в таком формате?

**Comment by halny123** [comment]
да

**Comment by daxartio** [comment]
Попробуй переделать вот этот шаблон https://github.com/sportorg/pysport/blob/dev/templates/start/3_times.html

**Comment by halny123** [comment]
Пробовал ) но тяжело быть далеким от программирования ))
Получилось все что хотел, но не могу понять как в нем выводить минуты на которых никто не стартует.
Вот что получил 
{% extends "base.html" %}

{% block title %}Start Times{% endblock %}

{% block head %}
{{ super() }}
{% endblock %}

{% block content %}
<div id="start-times-tables"></div>
{% raw %}
<style>
    @media print {
        table.sportorg-table th {
            text-align: left;
        }

        table.sportorg-table td {
            padding-top: 15px;
            border-bottom: 1px solid black;
        }
    }
</style>
<script>
    var race = {% endraw %}{{race|tojson}}{% raw %};
    racePreparation(race);

    function getStartTimes() {
        var times = {};
		
        for (var _i = 0, _a = race.persons; _i < _a.length; _i++) {
            var person = _a[_i];
			
            if (times[person.start_time]) {
                var val = times[person.start_time][person.group && person.group.start_corridor || 0];
                if (val) {
                    val += ', ' + person.surname + ' ' + person.name;
                }
                else {
                    val =  person.surname + ' ' + person.name;
                }
                times[person.start_time][person.group && person.group.start_corridor || 0] = val;
            }
            else {
                times[person.start_time] = {};
                times[person.start_time][person.group && person.group.start_corridor || 0] = person.surname + ' ' + person.name;
            }
        }
        var results = [];
        for (var start_time in times) {
		  times[start_time]['start_time'] = +start_time;
//            times[start_time]['start_time_str'] = toHHMMSS(+start_time);
			times[start_time]['start_time_str'] = start_time/60000 + ".mp3;";
            results.push(times[start_time])
        }
        results.sort(function (a, b) {
            return a.start_time - b.start_time;
        });
        return results;
    }
    var Fields = {
        fields: [
            {key: 'start_time_str', title: 'Время'}
        ],
        init: function () {
            var start_corridors = {};
            for (var _i = 0, _a = race.groups; _i < _a.length; _i++) {
                var group = _a[_i];
                start_corridors[group.start_corridor] = group.start_corridor;
            }
            for (var c in start_corridors) {
                this.fields.push({key: c, title: start_corridors[c]})
            }
            return this;
        }
    }.init();
    function render() {
        var resultBlock = document.getElementById('start-times-tables');
        resultBlock.innerHTML = '';
        resultBlock.appendChild(new TableGenerator(getStartTimes(), Fields.fields).getTable({className: 'sportorg-table'}));
    }
    render();
</script>
{% endraw %}
{% endblock %}

**Comment by halny123** [comment]
Пробовал ) но тяжело быть далеким от программирования ))
Получилось все что хотел, но не могу понять как в нем выводить минуты на которых никто не стартует.
Вот что получил пока .

**Comment by halny123** [comment]
{% extends "base.html" %}

{% block title %}Start Times{% endblock %}

{% block head %}
{{ super() }}
{% endblock %}

{% block content %}
<div id="start-times-tables"></div>
{% raw %}
<style>
    @media print {
        table.sportorg-table th {
            text-align: left;
        }

        table.sportorg-table td {
            padding-top: 15px;
            border-bottom: 1px solid black;
        }
    }
</style>
<script>
    var race = {% endraw %}{{race|tojson}}{% raw %};
    racePreparation(race);

    function getStartTimes() {
        var times = {};
		
        for (var _i = 0, _a = race.persons; _i < _a.length; _i++) {
            var person = _a[_i];
			
            if (times[person.start_time]) {
                var val = times[person.start_time][person.group && person.group.start_corridor || 0];
                if (val) {
                    val += ', ' + person.surname + ' ' + person.name;
                }
                else {
                    val =  person.surname + ' ' + person.name;
                }
                times[person.start_time][person.group && person.group.start_corridor || 0] = val;
            }
            else {
                times[person.start_time] = {};
                times[person.start_time][person.group && person.group.start_corridor || 0] = person.surname + ' ' + person.name;
            }
        }
        var results = [];
        for (var start_time in times) {
		  times[start_time]['start_time'] = +start_time;
//            times[start_time]['start_time_str'] = toHHMMSS(+start_time);
			times[start_time]['start_time_str'] = start_time/60000 + ".mp3;";
            results.push(times[start_time])
        }
        results.sort(function (a, b) {
            return a.start_time - b.start_time;
        });
        return results;
    }
    var Fields = {
        fields: [
            {key: 'start_time_str', title: 'Время'}
        ],
        init: function () {
            var start_corridors = {};
            for (var _i = 0, _a = race.groups; _i < _a.length; _i++) {
                var group = _a[_i];
                start_corridors[group.start_corridor] = group.start_corridor;
            }
            for (var c in start_corridors) {
                this.fields.push({key: c, title: start_corridors[c]})
            }
            return this;
        }
    }.init();
    function render() {
        var resultBlock = document.getElementById('start-times-tables');
        resultBlock.innerHTML = '';
        resultBlock.appendChild(new TableGenerator(getStartTimes(), Fields.fields).getTable({className: 'sportorg-table'}));
    }
    render();
</script>
{% endraw %}
{% endblock %}

**Comment by halny123** [comment]
<
{% extends "base.html" %}

{% block title %}Start Times{% endblock %}

{% block head %}
{{ super() }}
{% endblock %}

{% block content %}
<div id="start-times-tables"></div>
{% raw %}
<style>
    @media print {
        table.sportorg-table th {
            text-align: left;
        }

        table.sportorg-table td {
            padding-top: 15px;
            border-bottom: 1px solid black;
        }
    }
</style>
<script>
    var race = {% endraw %}{{race|tojson}}{% raw %};
    racePreparation(race);

    function getStartTimes() {
        var times = {};
		
        for (var _i = 0, _a = race.persons; _i < _a.length; _i++) {
            var person = _a[_i];
			
            if (times[person.start_time]) {
                var val = times[person.start_time][person.group && person.group.start_corridor || 0];
                if (val) {
                    val += ', ' + person.surname + ' ' + person.name;
                }
                else {
                    val =  person.surname + ' ' + person.name;
                }
                times[person.start_time][person.group && person.group.start_corridor || 0] = val;
            }
            else {
                times[person.start_time] = {};
                times[person.start_time][person.group && person.group.start_corridor || 0] = person.surname + ' ' + person.name;
            }
        }
        var results = [];
        for (var start_time in times) {
		  times[start_time]['start_time'] = +start_time;
//            times[start_time]['start_time_str'] = toHHMMSS(+start_time);
			times[start_time]['start_time_str'] = start_time/60000 + ".mp3;";
            results.push(times[start_time])
        }
        results.sort(function (a, b) {
            return a.start_time - b.start_time;
        });
        return results;
    }
    var Fields = {
        fields: [
            {key: 'start_time_str', title: 'Время'}
        ],
        init: function () {
            var start_corridors = {};
            for (var _i = 0, _a = race.groups; _i < _a.length; _i++) {
                var group = _a[_i];
                start_corridors[group.start_corridor] = group.start_corridor;
            }
            for (var c in start_corridors) {
                this.fields.push({key: c, title: start_corridors[c]})
            }
            return this;
        }
    }.init();
    function render() {
        var resultBlock = document.getElementById('start-times-tables');
        resultBlock.innerHTML = '';
        resultBlock.appendChild(new TableGenerator(getStartTimes(), Fields.fields).getTable({className: 'sportorg-table'}));
    }
    render();
</script>
{% endraw %}
{% endblock %}
>

**Comment by daxartio** [comment]
Тут есть только массив участников. Но может быть, что участники стартуют с интервалом и между ними никого нет. Здесь просто надо пройтись по списку и добавлять время между ними, которого нет. В js у списка есть метод splice, который принимает 3 аргумента

```
var list = [];
list.splice(0, 0, 'Время, которого нет');
list.splice(1, 0, 'Время, которого нет 2');
```

В общем тебе надо пройтись по списку и сравнить время текущего элемента и предыдущего и если между ними есть разница большая требуемому, например, больше одной минуты, то добавлять эти минуты. Так ты сможешь вывести минуты, на которых никто не стартует
