### ISSUE TITLE
Неправильно считываются некоторые чипы через BSM-8

### ISSUE THREAD

**Issue by kbats183** [sportorg/pysport#317]
При считывании некоторых чипов: si5, si8, si9 через станцию BSM-8 номера кп и время отметки считываются не правильно. За один день соревнований (150 участников) 5 чипов пришлось считывать в SIConfig и вручную переносить в sportorg. Проблема работает в SportOrg 1.2 (из exe) и в SportOrg 1.3 (из python). Со старой станцией BSM-7 такой проблемы нет.
Должно быть:
52 12:06:38
53 12:18:05
47 12:20:31
48 12:22:51
54 12:26:42
49 12:40:10
41 12:44:33
51 12:48:47
44 12:51:15
Считывается:
32 02:17:04
32 02:17:04
32 02:17:04
32 02:17:04
32 02:17:04
32 02:17:04
32 02:17:04
32 02:17:04
45 19:59:29

**Comment by sergeikobelev** [comment]
Спасибо за замечание, будем тестировать, завтра возьму BSM-8 станцию для тестов.

**Comment by sergeikobelev** [comment]
Тестировал на нескольких соревнованиях на 1.4, в разных режимах  (с legacy protocol и без) c BSM-8 - пока такой проблемы не было.
Нужен файл log/sportorg.log - там пишется взаимодействие со станциями.

**Comment by kbats183** [comment]
[sportorg-.log](https://github.com/sportorg/pysport/files/2847854/sportorg-.log)
[si20190108.log](https://github.com/sportorg/pysport/files/2847856/si20190108.log)

**Comment by sergeikobelev** [comment]
Привет. Все понятно, это чипы SI-6 (6-значные номера 500001-999999). 
Нужно отключить в настройках мастер-станции опцию "SI-Card6 192 отметки", с ней приходит больше блоков для SI-Card6, 10, 11, SIAC.  Я сделаю поддержку этого режима, но лучше его не использовать - чтение этих моделей чипов в 2 раза медленнее с ним.

**Comment by kbats183** [comment]
Добрый вечер. Хорошо, проверим завтра

**Comment by kbats183** [comment]
Все получилось. Спасибо
