### ISSUE TITLE
Низкая производительность при работе с числом участников более 1000

### ISSUE THREAD

**Issue by livello** [sportorg/pysport#329]
Программа нагружает только 1 ядро.
База на 3500 участников:
1. fx 8350 переключение вкладок и правка данных участника подвешивает программу на 3c
2. древний проц 2011 года Intel(R) Core(TM) i7 CPU M 620 подвисания уже 5с. В принципе жить можно
Заметил, что задержка будет увеличиваться линейно с ростом числа участников. Если их 7000, это уже 6с и 10с соответственно. Что куда ощутимее.

**Comment by daxartio** [comment]
В планах есть увеличить производительность

**Comment by daxartio** [comment]
Нужно проверить на актуальность. Вроде проблема решена после этого PR #346

**Comment by daxartio** [comment]
#346
