### ISSUE TITLE
Параметризация шаблонов для подсчета суммы

### ISSUE THREAD

**Issue by kbats183** [sportorg/pysport#399]
Есть много различных способов для подсчета результатов по сумме нескольких дней: сумма очков, сумма времен, сумма мест.
При этом в качестве идентификатора участника может быть: фамилия имя, номер или, например, национальный код (использование последнего было бы полезно при использовании различных номеров в разные дни во избежание проблем с совпадающими именами).

Чтобы не плодить шаблоны на каждый случай жизни, стоит сделать настройку параметра, по которому следует сравнивать участников разных дней (имя, номер), или на уровне HTML страницы (под кнопкой свернуть/развернуть настройки), или на уровне программы (например, в форме настройки->многодневные соревнования). Вероятно, второй вариант лучше.

**Comment by sergeikobelev** [comment]
В новых шаблонах связываем сумму по фамилии + имени + группе. Считается, что на нормальных стартах по умолчанию каждый день выдаются новые номера, поэтому проще связать участников разных дней именно так. Сталкивался с тем, что однажды из разных регионов приехали 2 Захаровых Владимира, пришлось одному отчество добавить, но это стандартный подход, который применяется например в тех же рейтингах orgeo.
