### ISSUE TITLE
Некорректное отображение чекбоксов и других полей

### ISSUE THREAD

**Issue by upmix** [sportorg/pysport#413]
Во первых спасибо за программу!
Некорректно отображаются некоторые поля: чекбоксы, время  и тд
![2023-05-16_20-25-34](https://github.com/sportorg/pysport/assets/60343820/7a7c10f1-71fc-4f92-95f1-b9f02631526a)
Windows 10 64

**Comment by sergeikobelev** [comment]
Исправлено где-то в начале 2023, обновление будет доступно в версии 1.7.
