### ISSUE TITLE
Некорректно присваиваются номер

### ISSUE THREAD

**Issue by upmix** [sportorg/pysport#414]
При выборе варианта Коридор + Минута, вместо коридора: 1,2,3... присваиваются четные цифры 0,2,4...
![2023-05-16_20-43-29](https://github.com/sportorg/pysport/assets/60343820/e4d15d86-7045-429d-9161-e83678d27627)
![2023-05-16_20-46-34](https://github.com/sportorg/pysport/assets/60343820/30b93e7b-5112-41b5-8100-58ffcf027ffe)
![2023-05-16_20-48-24](https://github.com/sportorg/pysport/assets/60343820/b114f39b-3fc7-4fb2-b01b-aa9e23b69a5d)

**Comment by sergeikobelev** [comment]
Добрый день. Понятие "коридор + минута" тут весьма условное. При количестве участников более 100 человек в коридоре этот коридор может быть связан с несколькими сотнями номеров, поэтому номера просто присваиваются с 1 в первом по порядке коридоре, далее следующая сотня присваивается следующему коридору и т.д.
