### ISSUE TITLE
Produce AppImage package using Travis CI

### ISSUE THREAD

**Issue by Symbian9** [sportorg/pysport#60]
Here are FAQ and tools:
* https://github.com/AppImage/AppImageKit/wiki/
  * https://github.com/AppImage/AppImageKit/wiki/Bundling-Python-apps
* https://github.com/probonopd/linuxdeployqt
* https://github.com/probonopd/uploadtool

### REFERENCE
* https://github.com/KmolYuan/Pyslvs-PyQt5/issues/3
  * https://github.com/KmolYuan/Pyslvs-PyQt5/blob/dev0.9/appimage_recipe.sh
* https://github.com/AppImage/AppImageKit/wiki/AppImages

**Comment by daxrt** [comment]
Thank you, we will definitely see.

**Comment by Symbian9** [comment]
Here is list of apps that already use AppImage packaging on AppImageHub
* http://appimage.github.io/apps

**Comment by daxrt** [comment]
Ok
